<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- Thêm dòng này để VS nhận diện và chạy T4 khi build -->
    <TransformOnBuild>true</TransformOnBuild>
    <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>
    <TransformOutOfDateOnly>false</TransformOutOfDateOnly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rental.Application\Rental.Application.csproj" />
    <ProjectReference Include="..\Rental.Mail\Rental.Mail.csproj" />
    <ProjectReference Include="..\Rental.Hangfire\Rental.Hangfire.csproj" />
  </ItemGroup>
</Project>
